kubernetes_version: "1.35.0"
container_runtime: "containerd"

# CIDR cho pod và service (không được trùng với CIDR của VPC)
pod_cidr: "10.244.0.0/20"
service_cidr: "10.96.0.0/12"
cluster_domain: "cluster.local"

# Network plugin
k8s_network_plugin: "calico"
calico_version: "v3.32.0"


