; Inventory mẫu - bạn chỉnh lại IP/hostname cho phù hợp hạ tầng thực tế

[k8s_master]
k8s-master ansible_host=172.31.24.204

[k8s_workers]
k8s-worker1 ansible_host=172.31.31.235
k8s-worker2 ansible_host=172.31.26.217

[k8s_cluster:children]
k8s_master
k8s_workers

[pg_master]
pg-master ansible_host=10.10.9.15

[pg_slave]
pg-slave ansible_host=10.10.9.16

[postgres_cluster:children]
pg_master
pg_slave

[rabbitmq]
rabbit ansible_host=152.42.183.53
# rabbit2 ansible_host=10.0.0.31


