; Inventory mẫu - bạn chỉnh lại IP/hostname cho phù hợp hạ tầng thực tế

[k8s_master]
k8s-master-1 ansible_host=52.77.241.185 ansible_user=ubuntu

[k8s_workers]
k8s-worker-1 ansible_host=47.128.144.108 ansible_user=ubuntu
k8s-worker-2 ansible_host=13.212.88.61 ansible_user=ubuntu

[cluster_k8s:children]
k8s_master
k8s_workers

; [pg_master]
; pg-master ansible_host=10.10.9.15

; [pg_slave]
; pg-slave ansible_host=10.10.9.16

; [postgres_cluster:children]
; pg_master
; pg_slave

; [rabbitmq]
; rabbit ansible_host=152.42.183.53
# rabbit2 ansible_host=10.0.0.31

[nginx]
nginx-1 ansible_host=db


