nginx_sites:
  - nginx_site_name: mail-merge.tech
    nginx_server_name: mail-merge.tech
    nginx_root: /var/www/html
    nginx_listen_port: 80
    nginx_proxy_pass: https://localhost:3000
    certbot_email: maithanhhai9x@gmail.com
    certbot_domains:
      - mail-merge.tech

  # - nginx_site_name: rancher.hai-alison.click
  #   nginx_server_name: rancher.hai-alison.click
  #   nginx_root: /var/www/html
  #   nginx_listen_port: 80
  #   nginx_proxy_pass: https://localhost:8443
  #   certbot_email: maithanhhai9x@gmail.com
  #   certbot_domains:
  #     - rancher.hai-alison.click