---
nginx_sites:
  - nginx_site_name: mail-merge.tech
    nginx_server_name: mail-merge.tech
    nginx_root: /var/www/html
    nginx_listen_port: 80
    certbot_email: maithanhhai9x@gmail.com
    certbot_domains:
      - mail-merge.tech
